name: Build KeyboardOverlay

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Build Debug (Universal Binary)
        run: |
          xcodebuild -project KeyboardOverlay.xcodeproj \
                     -scheme "KeyboardOverlay" \
                     -configuration Debug \
                     -derivedDataPath ./DerivedData \
                     ARCHS="x86_64 arm64" \
                     build

      - name: Build Release (Universal Binary)
        run: |
          xcodebuild -project KeyboardOverlay.xcodeproj \
                     -scheme "KeyboardOverlay" \
                     -configuration Release \
                     -derivedDataPath ./DerivedData \
                     ARCHS="x86_64 arm64" \
                     build

      - name: Archive Release (Universal Binary)
        run: |
          xcodebuild -project KeyboardOverlay.xcodeproj \
                     -scheme "KeyboardOverlay" \
                     -configuration Release \
                     -derivedDataPath ./DerivedData \
                     -archivePath ./KeyboardOverlay.xcarchive \
                     ARCHS="x86_64 arm64" \
                     archive

      - name: Create App Bundle
        run: |
          cp -R "./DerivedData/Build/Products/Release/Keyboard Overlay.app" \
                "./Keyboard Overlay.app"

      - name: Create DMG
        run: |
          # Create a temporary directory for DMG contents
          mkdir -p dmg_contents
          cp -R "./Keyboard Overlay.app" dmg_contents/

          # Create a symbolic link to Applications folder
          ln -s /Applications dmg_contents/Applications

          # Create the DMG
          hdiutil create -volname "Keyboard Overlay" \
                         -srcfolder dmg_contents \
                         -ov -format UDZO \
                         "Keyboard Overlay.dmg"

      - name: Upload Debug Build
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardOverlay-Debug
          path: ./DerivedData/Build/Products/Debug/Keyboard Overlay.app

      - name: Upload Release Build
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardOverlay-Release
          path: "./Keyboard Overlay.app"

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardOverlay-Archive
          path: ./KeyboardOverlay.xcarchive

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: KeyboardOverlay-DMG
          path: "./Keyboard Overlay.dmg"
